#!/usr/bin/env python3
"""Reusable avatar dress-up library: chroma-key extraction + z-order compositing.

Pipeline (validated 2026-06-28):
  1. Each part is generated by codex/agy on a SOLID MAGENTA (#FF00FF) background,
     positioned/scaled to fit a fixed base (e.g. base_female.png).
  2. chroma_key_defringe() turns it into a clean transparent RGBA part (magenta
     removed, edge halo eroded + decontaminated).
  3. bbox()/crop_with_offset() gives a tight part image + its full-canvas offset.
  4. compose() stacks parts over the base by z-order.

Used by the dress-up driver and the SwiftUI export. Keep this pure/testable.
"""
from __future__ import annotations
import numpy as np
from PIL import Image, ImageFilter
from scipy import ndimage

MAGENTA = np.array([255, 0, 255])


def chroma_key_defringe(img: Image.Image, *, dist_threshold: int = 120,
                        bg_seed_threshold: int = 40, halo_px: int = 3,
                        erode_px: int = 2, decontaminate: bool = True,
                        ring_px: int = 3) -> Image.Image:
    """Magenta-keyed RGBA with eroded alpha and magenta-cast removed at edges.

    The background is the actual magenta PAINT (any pixel within `bg_seed_threshold`
    of pure #FF00FF — the backdrop AND enclosed pure-magenta gaps between hair
    strands), plus only a BOUNDED anti-aliased halo: the `near_mag` pixels within
    `halo_px` of that paint.

    Crucially it does NOT flood unbounded through every magenta-ish pixel. A pink or
    purple foreground part (magenta-ish but not pure) keeps its body opaque whether
    it is enclosed by other parts OR exposed directly to the backdrop — an exposed
    pink edge only loses its ~`halo_px` antialiased rim, not the whole part. This
    fixes the old global key that punched holes in / desaturated pink parts.

    Convention: foreground art must never use colors within `bg_seed_threshold` of
    pure magenta (use normal pinks like #FF69B4); #FF00FF is reserved for background.

    Decontamination only touches the foreground edge ring (within `ring_px` of the
    keyed background), so legitimately pink/purple interiors are left untouched.
    """
    rgb = np.asarray(img.convert("RGB")).astype(np.int16)
    dist = np.abs(rgb - MAGENTA).sum(axis=2)
    near_mag = dist <= dist_threshold          # backdrop + halo + magenta-ish foreground
    pure_mag = dist <= bg_seed_threshold        # the actual magenta paint only

    # background = the magenta paint + a bounded antialiased halo around it.
    if halo_px > 0:
        halo = ndimage.binary_dilation(pure_mag, iterations=halo_px) & near_mag
        background = pure_mag | halo
    else:
        background = pure_mag
    alpha = np.where(background, 0, 255).astype(np.uint8)
    if erode_px > 0:
        size = erode_px * 2 + 1
        alpha = np.asarray(Image.fromarray(alpha).filter(ImageFilter.MinFilter(size)))
    if decontaminate:
        # only de-spill the foreground edge ring adjacent to the keyed background.
        ring = ndimage.binary_dilation(background, iterations=ring_px) & ~background
        r, g, b = rgb[..., 0], rgb[..., 1], rgb[..., 2]
        # magenta-TINTED edge pixels only (high R AND high B vs G = spill).
        spill = (r > g + 40) & (b > g + 40) & ring
        rgb[..., 0] = np.where(spill, np.minimum(r, g + 25), r)  # tame red spill
        rgb[..., 2] = np.where(spill, np.minimum(b, g + 25), b)  # tame blue spill
    out = np.dstack([np.clip(rgb, 0, 255).astype(np.uint8), alpha])
    return Image.fromarray(out, "RGBA")


def bbox(rgba: Image.Image) -> tuple[int, int, int, int] | None:
    """(left, top, right, bottom) of non-transparent pixels, or None if empty."""
    a = np.asarray(rgba)[..., 3]
    ys, xs = np.where(a > 0)
    if not len(xs):
        return None
    return int(xs.min()), int(ys.min()), int(xs.max()) + 1, int(ys.max()) + 1


def crop_with_offset(rgba: Image.Image) -> tuple[Image.Image, int, int]:
    """Crop to alpha bbox; return (cropped, offset_x, offset_y) full-canvas-relative."""
    box = bbox(rgba)
    if box is None:
        return rgba, 0, 0
    left, top, right, bottom = box
    return rgba.crop(box), left, top


def compose(base: Image.Image, layers: list[Image.Image]) -> Image.Image:
    """Alpha-composite full-canvas RGBA layers over base, in given (low->high) order."""
    out = base.convert("RGBA")
    for layer in layers:
        out.alpha_composite(layer.convert("RGBA"))
    return out
